# Site settings
title: Jacob Wunder&#146;s Blog
email: none of your beez-wax@hotnetmail.org
description: > # this means to ignore newlines until "baseurl:"
  I&#146;m just a kid, speaking into the void...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  jaywunder
# Build settings
markdown: redcarpet
